#### general settings
name: EDVR_train_num500_5frame
use_tb_logger: false
model: video_base
distortion: sr
scale: 4
gpu_ids: [4,5]

#### datasets
datasets:
  train:
    name: REDS
    mode: REDS
    interval_list: [1]
    random_reverse: false
    border_mode: false
    dataroot_GT: /home/lzy/Downloads/EDVR-master/datasets/pngs/my_dataset_gt.lmdb
    dataroot_LQ: /home/lzy/Downloads/EDVR-master/datasets/pngs/my_dataset_input.lmdb
    cache_keys: ~

    N_frames: 5
    use_shuffle: true
    n_workers: 4  # per GPU
    batch_size: 2
    GT_size: 1200
    LQ_size: 300
    use_flip: true
    use_rot: true
    color: RGB
    cache_data: false

#### network structures
network_G:
  which_model_G: EDVR
  nf: 64
  nframes: 5
  groups: 8
  front_RBs: 5
  back_RBs: 10
  predeblur: true
  HR_in: false
  w_TSA: true


#### path
path:
  pretrain_model_G: ~
  strict_load: false
  resume_state: ~

#### training settings: learning rate scheme, loss
train:
  lr_G: !!float 4e-4
  lr_scheme: CosineAnnealingLR_Restart
  beta1: 0.9
  beta2: 0.99
  niter: 600000
  ft_tsa_only: 50000
  warmup_iter: -1  # -1: no warm up
  T_period: [50000, 100000, 150000, 150000, 150000]
  restarts: [50000, 150000, 300000, 450000]
  restart_weights: [1, 1, 1, 1]
  eta_min: !!float 1e-7

  pixel_criterion: cb
  pixel_weight: 1.0
  val_freq: !!float 1e4

  manual_seed: 0

#### logger
logger:
  print_freq: 50
  save_checkpoint_freq: !!float 5e3
